### ISSUE TITLE
eclipse.ini settings of the snap can't be changed

### ISSUE THREAD

**Issue by codeHorse87** [snapcrafters/eclipse#28]
Hi,

Thanks for crafting the snap! I came across the situation that I needed to add certain module paths in the eclipse.ini configuration. This is not possilbe as the ini file is by the snap a read-only mount. A possible workaround is to define all the eclipse.ini parameters as start parameters in a script. However, I propose that the snap provides commands to set and remove eclipse.ini parameters. 

Regards
Marco

**Comment by anubias** [comment]
Upvote for this issue.

**Comment by brazso** [comment]
You may change the location of the eclipse.ini file if there are more arguments to be set/altered there.

Using Linux/KDE there is  a dektop file/icon for Eclipse after snap installation. I copied that desktop file to a new one (on a new name) in ~/Desktop directory. 
`cp eclipse_eclipse.desktop eclipse_home.desktop`
The following line was modified there in an editor, _launcher.ini_ parameter has been added only:
`Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/eclipse_eclipse.desktop /snap/bin/eclipse %f --launcher.ini ~/snap/eclipse/current/eclipse.ini`
Finally I copied the original read-only eclipse.ini to the afores-set location.
`cp /snap/eclipse/current/eclipse.ini ~/snap/eclipse/current`
Starting the new desktop icon, the eclipse ini profile is loaded from the copied and editable eclipse.ini located under userdir instead of the original read-only mounted snap filesystem.

**Comment by lysz210** [comment]
I think @brazso idea is very good and we can try to do something similar during installation by:

1. make a backup copy of eclipse.ini
2. move eclipse.ini into ~/snap/eclipse/$CURRENT_VERSION/eclipse.ini with user as owner
3. make a link from /snap/eclipse/$CURRENT_VERSION/ to the moved eclipse.ini
This way the eclipse.ini sould be editable by user anche eclipse. Lombok p2 plugin must edit it to run correctly.

If there are some other plugins that require this it can be done.
Is this possible? (I'm not a snap developer).
